version: '3'
services:
    golang:
        build:
            context: .
            # dockerfile: DockerFile
        # command: /bin/sh -c "go run main.go"
        stdin_open: true
        tty: true
        volumes:
            - ..:/go/src/app
        ports:
            - 8080:8080
        environment:
            - PORT=8080
