package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"
	"fmt"
	"student-laboratory-matching-app/graph/model"
)

// CreateStudent is the resolver for the createStudent field.
func (r *mutationResolver) CreateStudent(ctx context.Context, input model.NewStudent) (*model.Student, error) {
	panic(fmt.Errorf("not implemented: CreateStudent - createStudent"))
}

// Student is the resolver for the student field.
func (r *queryResolver) Student(ctx context.Context, id string) (*model.Student, error) {
	return r.Srv.GetStudentById(id)
}

// University is the resolver for the university field.
func (r *studentResolver) University(ctx context.Context, obj *model.Student) (*model.University, error) {
	return r.Srv.GetUniversityById(obj.University.ID)
}

// Prefecture is the resolver for the prefecture field.
func (r *studentResolver) Prefecture(ctx context.Context, obj *model.Student) (*model.Prefecture, error) {
	return r.Srv.GetPrefectureById(obj.Prefecture.ID)
}

// Prefecture is the resolver for the prefecture field.
func (r *universityResolver) Prefecture(ctx context.Context, obj *model.University) (*model.Prefecture, error) {
	return r.Srv.GetPrefectureById(obj.Prefecture.ID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Student returns StudentResolver implementation.
func (r *Resolver) Student() StudentResolver { return &studentResolver{r} }

// University returns UniversityResolver implementation.
func (r *Resolver) University() UniversityResolver { return &universityResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type studentResolver struct{ *Resolver }
type universityResolver struct{ *Resolver }
